---
swagger: '2.0'
info:
  version: '1.0'
  title: proof-of-concept
paths:
  "/hello/{name}":
    get:
      responses: {}
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: "${lambda_invocation_arn}"
        passthroughBehavior: when_no_match
    post:
      responses: {}
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: "${lambda_invocation_arn}"
        passthroughBehavior: when_no_match
