name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 13 * * 1' 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.4
        terraform_wrapper: false

    - name: Install lstk
      run: npm install -g @localstack/lstk

    - name: Execute tests
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        DEBUG: 1
      timeout-minutes: 100
      run: make test-ci-all
